version: '3.8'
services:
  singlestoredb:
    image: singlestore/cluster-in-a-box
    container_name: singlestoredb
    volumes:
      - .:/root
    ports:
      - 3306:3306
      - 8080:8080
    env_file:
      - ./.env
    environment:
      START_AFTER_INIT: 'Y'
